### ISSUE TITLE
Footnote Feature fails on Sublime Text 3

### ISSUE THREAD

**Issue by shaaati** [mgaitan/sublime-rst-completion#78]
On Sublime Text 3, the footnote shortcut fails and prints the following to the console:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "footnotes in /Users/phil/Library/Application Support/Sublime Text 3/Installed Packages/Restructured Text (RST) Snippets.sublime-package", line 109, in run
TypeError: begin_edit() missing 2 required positional arguments: 'edit_token' and 'cmd'
```

As far as I found out, Sublime Text 3 has changed the way begin_edit() is used.

**Comment by jimklo** [comment]
Found this out too, and just updated to ST3. Here's a PR to fix. Enjoy!
